name: GitHub Actions Demo
run-name: NETSprinkler.WorkerApi Build
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    env:      
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}  
      DOCKER_TARGET_PLATFORM: linux/arm/v7   
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: neichmann/netsprinkler.apiworker:latest
          file: NETSprinkler.ApiWorker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7            